language: ruby
cache: bundler
rvm:
  - 2.2.3
gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
notifications:
  email: false
